services:
  app:
    build: .
    restart: on-failure
    ports:
      - "80:80"
    env_file:
      - .env
    environment:
      TZ: Europe/Berlin
      HTTP_PORT: 80
      LOG_LEVEL: debug
      DEPLOYMENT_CONFIG_FILE_NAME: /.compose-webhook.y(a)?ml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock