name: Tests

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'README.md'
      - 'docs/**'

jobs:
  test:
    name: Run Acceptance Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: go mod download
      - run: go test -v -race -coverprofile=coverage.out -covermode=atomic ./... -timeout 5m
        timeout-minutes: 5
        env:
          WEBHOOK_SECRET: test_Secret1
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673 # v4.5.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
